const BACKEND_API_URL = process.env.NEXT_PUBLIC_BACKEND_API_URL
const STORAGE_API_URL = process.env.NEXT_PUBLIC_STORAGE_API_URL
const NOTIFICATION_API_URL = process.env.NEXT_PUBLIC_NOTIFICATION_API_URL
const QUIZ_SERVICE_API_URL = process.env.NEXT_PUBLIC_QUIZ_SERVICE_API_URL

export const ROUTE_ALIAS = {
    '/core/': BACKEND_API_URL,
    '/st/': STORAGE_API_URL,
    '/noti/': NOTIFICATION_API_URL,
    '/quiz-svc': QUIZ_SERVICE_API_URL
}
