export const SUBSCRIBE_NOTIFICATION_EVENT = 'SUBSCRIBE_NOTIFICATION_EVENT'
export const UN_SUBSCRIBE_NOTIFICATION_EVENT = 'UN_SUBSCRIBE_NOTIFICATION_EVENT'
export const NEW_NOTIFICATION_EVENT = 'NEW_NOTIFICATION_EVENT'
export const BOOKING_END_CLASS_EVENT = 'BOOKING_END_CLASS_EVENT'
export const SUBSCRIBE_BOOKING_CHANGES_EVENT = 'SUBSCRIBE_BOOKING_CHANGES_EVENT'
export const UN_SUBSCRIBE_BOOKING_CHANGES_EVENT =
    'UN_SUBSCRIBE_BOOKING_CHANGES_EVENT'
